# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(160, 550, 631, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.left_btn.setObjectName("left_btn")
        self.horizontalLayout_2.addWidget(self.left_btn)
        self.right_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.right_btn.setObjectName("right_btn")
        self.horizontalLayout_2.addWidget(self.right_btn)
        self.mirror_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.mirror_btn.setObjectName("mirror_btn")
        self.horizontalLayout_2.addWidget(self.mirror_btn)
        self.sharp_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.sharp_btn.setObjectName("sharp_btn")
        self.horizontalLayout_2.addWidget(self.sharp_btn)
        self.bw_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.bw_btn.setObjectName("bw_btn")
        self.horizontalLayout_2.addWidget(self.bw_btn)
        self.files_list = QtWidgets.QListWidget(parent=self.centralwidget)
        self.files_list.setGeometry(QtCore.QRect(10, 60, 141, 521))
        self.files_list.setObjectName("files_list")
        self.dir_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.dir_btn.setGeometry(QtCore.QRect(10, 20, 141, 23))
        self.dir_btn.setObjectName("dir_btn")
        self.photo_lb = QtWidgets.QLabel(parent=self.centralwidget)
        self.photo_lb.setGeometry(QtCore.QRect(200, 270, 47, 13))
        self.photo_lb.setObjectName("photo_lb")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.left_btn.setText(_translate("MainWindow", "Вліво"))
        self.right_btn.setText(_translate("MainWindow", "Вправо"))
        self.mirror_btn.setText(_translate("MainWindow", "Дзеркало"))
        self.sharp_btn.setText(_translate("MainWindow", "Різкість"))
        self.bw_btn.setText(_translate("MainWindow", "Ч/Б"))
        self.dir_btn.setText(_translate("MainWindow", "Папка"))
        self.photo_lb.setText(_translate("MainWindow", "картинка"))
